{{- if $.Values.teamcity.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tc.name" ( dict "ctx" $ ) }}-service-account
  labels:
    {{- include "tc.metadata.labels" ( dict "ctx" $ ) | indent 4 }}
automountServiceAccountToken: true
{{- end }}